#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum CHANNELID {
		CHANNEL_0, CHANNEL_1, CHANNEL_2, CHANNEL_3, CHANNEL_4, CHANNEL_5, CHANNEL_6, CHANNEL_7
		, CHANNEL_8, CHANNEL_9, CHANNEL_10, CHANNEL_11, CHANNEL_12, CHANNEL_13, CHANNEL_14, CHANNEL_15
		, MAXCHANNEL
	};

	enum DATATYPE {
		DATA_BOOL, DATA_BYTE, DATA_UBYTE, DATA_TCHAR, DATA_SHORT, DATA_USHORT,
		DATA_INT, DATA_UINT, DATA_LONG, DATA_ULONG, DATA_FLOAT, DATA_DOUBLE,
		DATA_VEC2, DATA_VEC3, DATA_VEC4, DATA_MAT, DATA_END
	};
}

namespace Engine
{
    enum GAMEOBJECT_TYPE
    {
        GAME_OBJECT,
        CAMERA_OBJECT,
        RENDER_OBJECT,
        OBJECT_END
    };

	enum PROTOTYPE_COMPONENT
	{
		RECTCOLOR,
		SINGLERECTTEX,
		RECTTEX,
		TERRAINTEX,
        TERRAINDUNGEONTEX,
		CUBETEX,

		TRANSFORM,

		TEXTURE,
		TEXTURE_TERRAIN,

        COLLIDER,
        SPHERE_COLLIDER,
        RECT_COLLIDER,

		COMPONENT_END
	};

    enum COL_TYPE
    {
        RECT_COL,
        SPHERE_COL,
        SQURARE_COL,
        COL_END
    };
    enum COL_STATE
    {
        ENTER_COL,
        STAY_COL,
        EXIT_COL, 
        COL_STATE_END
    };
}

#endif // Engine_Enum_h__

